test:
  name: fabric-benchmarks
  description: A simple fabric benchmark test.
  workers:
    number: 5
  rounds:
    - label: add-orders-1000
      description: Add single orders one at a time.
      txNumber: 1000
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 5
      workload:
        module: workloads/add-order.js
    
